# Generated by Django 4.2.11 on 2024-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0003_department_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
