# Generated by Django 4.2.11 on 2024-04-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_store_remove_department_users_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
