# Generated by Django 4.2.11 on 2024-04-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
