# Generated by Django 4.2.11 on 2024-04-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_department_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
