# Generated by Django 4.2.11 on 2024-04-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_store_owner_remove_user_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_name',
        ),
    ]
