# Generated by Django 4.2.11 on 2024-04-20 18:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('status', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('categoryslug', models.CharField(max_length=100)),
                ('createdby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=200, null=True)),
                ('categorycode', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
                ('createdby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Pc', 'Pc')], max_length=200, null=True)),
                ('barcode', models.CharField(max_length=300, null=True)),
                ('itemcode', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('single', models.BooleanField()),
                ('variable', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tax_type', models.CharField(blank=True, max_length=200, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_value', models.IntegerField(blank=True, null=True)),
                ('quantity_alert', models.IntegerField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('manuf_date', models.CharField(max_length=50, null=True)),
                ('exp_date', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.brand')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.category')),
                ('createdby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stotes.store')),
                ('subcategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.subcategory')),
            ],
        ),
    ]
