# Generated by Django 4.2.11 on 2024-04-25 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
