# Generated by Django 4.2.11 on 2024-04-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0002_alter_customers_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, choices=[('Restront', 'Restront'), ('Store', 'Store')], max_length=100, null=True),
        ),
    ]
