# Generated by Django 4.2.11 on 2024-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
