# Generated by Django 4.2.11 on 2024-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_store_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
