# Generated by Django 4.2.11 on 2024-04-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_category_store'),
        ('Sales', '0002_alter_sales_costumer_name_alter_salesreturn_customer'),
        ('Accounts', '0010_remove_user_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_owner',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
