# Generated by Django 4.2.11 on 2024-04-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Accounts', '0011_remove_department_store_remove_store_store_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
