# Generated by Django 4.2.11 on 2024-04-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
        ('Accounts', '0002_customers_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('grand_total', models.IntegerField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('due', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Accounts.customers')),
                ('product_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.products')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrence', models.CharField(max_length=20, null=True)),
                ('invoice', models.CharField(max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('grand_total', models.IntegerField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('due', models.ImageField(null=True, upload_to='')),
                ('biller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('costumer_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Accounts.customers')),
            ],
        ),
    ]
