# Generated by Django 4.2.11 on 2024-04-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(to='Products.products'),
        ),
    ]
