# Generated by Django 4.2.11 on 2024-04-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0003_department_user'),
        ('Sales', '0002_alter_sales_costumer_name_alter_salesreturn_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store'),
        ),
    ]
