# Generated by Django 4.2.11 on 2024-04-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0003_department_user'),
        ('Sales', '0003_sales_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store'),
        ),
    ]
