# Generated by Django 4.2.11 on 2024-04-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_store_owner_remove_user_department_and_more'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.store'),
        ),
    ]
