# Generated by Django 4.2.11 on 2024-04-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0001_initial'),
        ('Products', '0002_category_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store'),
        ),
    ]
