# Generated by Django 4.2.11 on 2024-04-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0003_department_user'),
        ('Products', '0003_alter_category_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store'),
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stotes.store'),
        ),
    ]
