# Generated by Django 4.2.11 on 2024-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_products_brand_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='single',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='variable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
