# Generated by Django 4.2.11 on 2024-04-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stotes', '0003_store_store_type'),
        ('Products', '0007_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Stotes.store'),
        ),
    ]
