# Generated by Django 4.2.11 on 2024-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_subcategory_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
