# Generated by Django 4.2.11 on 2024-04-26 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_brand_brand_alter_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='products/product_prev_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
